version: '3.1'

networks:
  devnet:

services:
  postgres01:
    container_name: postgres01
    image: postgres:9.6.17-alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./volume/postgres01:/var/lib/postgresql/data
      - ./scripts/createdb.sql:/docker-entrypoint-initdb.d/1-createdb.sql
      - ./scripts/init-auth-db.sh:/docker-entrypoint-initdb.d/2-init-auth-db.sh
    command: postgres
    ports:
      - 5432:5432
    networks:
      - devnet

#  mongo:
#    container_name: mongo
#    image: mongo
#    restart: always
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=example
#      - MONGO_INITDB_DATABASE=did-db
#      - MONGO_INITDB_USERNAME=tester
#      - MONGO_INITDB_PASSWORD=tester-password
#
#    ports:
#      - 27017:27017
#    volumes:
#      # why add this env var, see https://github.com/docker-library/mongo/issues/323
#      - ./home/mongodb:/home/mongodb
#      - ./volume/mongo-data:/data/db
#      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
#    networks:
#      - devnet
#
#  mongo-express:
#    container_name: mongo-express
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#    networks:
#      - devnet
